preset: laravel
risky: true
finder:
  name: "*.php"
  not-name: "*.blade.php"
disabled:
  - blank_line_after_opening_tag
  - single_blank_line_before_namespace
  - length_ordered_imports
  - concat_without_spaces
  - not_operator_with_successor_space
  - simplified_null_return
  - unalign_equals
enabled:
  - alpha_ordered_imports
  - no_blank_lines_before_namespace
  - concat_with_spaces
  - align_double_arrow_minimal
  - combine_consecutive_issets
  - combine_consecutive_unsets
  - compact_nullable_typehint
  - mb_str_functions
  - no_null_property_initialization
  - no_short_echo_tag
  - no_spaces_outside_offset
  - no_superfluous_elseif
  - no_unneeded_curly_braces
  - no_unneeded_final_method
  - no_useless_else
  - phpdoc_add_missing_param_annotation
  - phpdoc_align
  - phpdoc_order
  - phpdoc_separation
  - phpdoc_types_order
  - protected_to_private
  - semicolon_after_instruction
  - ternary_to_null_coalescing
  - align_equals_minimal
  - array_indentation
  - backtick_to_shell_exec
  - blank_line_before_throw
  - comment_to_phpdoc
  - const_visibility_required
  - dir_constant
  - doctrine_annotation_array_assignment
  - doctrine_annotation_braces
  - doctrine_annotation_indentation
  - doctrine_annotation_spaces
  - ereg_to_preg
  - explicit_indirect_variable
  - explicit_string_variable
  - fully_qualified_strict_types
  - function_to_constant
  - is_null
  - modernize_types_casting
  - multiline_comment_opening_closing
  - new_with_braces
  - no_alternative_syntax
  - no_blank_lines_after_return
  - no_empty_comment
  - no_extra_block_blank_lines
  - no_php4_constructor
  - ordered_class_elements
  - phpdoc_link_to_see
  - phpdoc_no_empty_return
  - phpdoc_property
  - phpdoc_return_self_reference
  - php_unit_construct
  - php_unit_dedicate_assert
  - php_unit_expectation
  - php_unit_mock
  - php_unit_namespaced
  - php_unit_no_expectation_annotation
  - php_unit_ordered_covers
  - php_unit_strict
  - pow_to_exponentiation
  - property_separation
  - random_api_migration
  - return_type_declaration
  - single_line_class_definition
  - standardize_increment
  - strict_comparison
  - strict_param
  - void_return